### ISSUE TITLE
5.6.1 Windows download - SPARQL pane not showing properly

### ISSUE THREAD

**Issue by pwin** [protegeproject/protege-distribution#35]
I downloaded the standard Windows distribution and loaded an ontology from a URL.  The SPARQL pane only showed a purple bar at the top and no content.  The error log showed the following:

   INFO  21:27:13  ------------------------------------ Protege -----------------------------------
   INFO  21:27:13  Protege Desktop
   INFO  21:27:13  Version 5.6.1, Build 
   INFO  21:27:13  
   INFO  21:27:13  
   INFO  21:27:13  ----------------------------------- Platform -----------------------------------
   INFO  21:27:13  Java: JVM 11.0.17+8  Memory: 2124M
   INFO  21:27:13  Language: en, Country: GB
   INFO  21:27:13  Framework: Apache Software Foundation (1.9) 
   INFO  21:27:13  OS: windows10 (10.0.0)
   INFO  21:27:13  Processor: x86-64

   INFO  21:27:13  
   INFO  21:27:13  ------------------------------------ Plugins -----------------------------------
   INFO  21:27:13  Plugin: Cellfie Protege 5.0+ Plugin (2.1.0)
   INFO  21:27:13  Plugin: OWL Code Generation Plug-in (2.0.0)
   INFO  21:27:13  Plugin: ELK Reasoner Protege Plug-in (0.5.0)
   INFO  21:27:13  Plugin: Existential Query (2.0.0)
   INFO  21:27:13  Plugin: Explanation Workbench (3.0.1)
   INFO  21:27:13  Plugin: OntoGraf (2.0.3)
   INFO  21:27:13  Plugin: DL Query (4.0.1)
   INFO  21:27:13  Plugin: HermiT Reasoner (1.4.3.456)
   INFO  21:27:13  Plugin: Browser View (OWLDoc) (3.0.3)
   INFO  21:27:13  Plugin: OWLViz (5.0.3)
   INFO  21:27:13  Plugin: Proof Utility Library (0.1.0)
   INFO  21:27:13  Plugin: OWLAPI RDF Library (3.0.0)
   INFO  21:27:13  Plugin: SPARQL Query Plugin (3.0.0)
   INFO  21:27:13  Plugin: SWRLTab Plugin (2.0.10)
   INFO  21:27:13  
   INFO  21:27:16  Creating and setting up empty (default) editor kit
   INFO  21:27:16  OWL API Version: 4.5.25.2023-02-15T19:15:49Z
   INFO  21:27:17  Cannot generate ontology catalog for ontology at http://www.semanticweb.org/user/ontologies/2023/1/untitled-ontology-13. URI scheme is not "file"
   INFO  21:27:19  ------------------------------- Auto-update Check ------------------------------
   INFO  21:27:19  Auto-update last performed: Mon Feb 27 21:15:59 GMT 2023
   INFO  21:27:19  Auto-update has been performed today.  Not performing it again.
   INFO  21:27:19  
   INFO  21:27:57  OWL API Version: 4.5.25.2023-02-15T19:15:49Z
   INFO  21:27:57  ------------------------------- Loading Ontology -------------------------------
   INFO  21:27:57  Loading ontology from https://ontologies.semanticarts.com/o/gistCore
   INFO  21:27:58  Notice: root element does not have an xml:base. Relative IRIs will be resolved against https://ontologies.semanticarts.com/o/gistCore
   INFO  21:27:59  Finished loading https://ontologies.semanticarts.com/o/gistCore
   INFO  21:27:59  Loading for ontology and imports closure successfully completed in 2396 ms
   INFO  21:27:59  
   INFO  21:28:00  ---------------------------- Disposing of Workspace ----------------------------
   INFO  21:28:00  Saved tab state for 'Individuals by class' tab
   INFO  21:28:00  Saved tab state for 'DL Query' tab
   INFO  21:28:00  Saved tab state for 'Entities' tab
   INFO  21:28:00  Saved tab state for 'Active ontology' tab
   INFO  21:28:00  Saved workspace
   INFO  21:28:00  Disposed of 'Individuals by class' tab
   INFO  21:28:00  Disposed of 'DL Query' tab
   INFO  21:28:00  Disposed of 'Entities' tab
   INFO  21:28:00  Disposed of 'Active ontology' tab
   INFO  21:28:00  Disposed of workspace
   INFO  21:28:00  
  ERROR  21:28:32  Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.NoSuchMethodError: 'void org.semanticweb.owlapi.rdf.model.AbstractTranslator.<init>(org.semanticweb.owlapi.model.OWLOntologyManager, org.semanticweb.owlapi.model.OWLOntology, boolean, org.semanticweb.owlapi.util.IndividualAppearance, org.semanticweb.owlapi.util.AxiomAppearance, java.util.concurrent.atomic.AtomicInteger, java.util.Map)'
	at org.protege.owl.rdf.impl.RDFTranslator.<init>(RDFTranslator.java:107) ~[na:na]
	at org.protege.owl.rdf.impl.RDFTranslator.translate(RDFTranslator.java:55) ~[na:na]
	at org.protege.owl.rdf.impl.OwlTripleStoreImpl.addAxiom(OwlTripleStoreImpl.java:99) ~[na:na]
	at org.protege.owl.rdf.Utilities.loadOwlTripleStore(Utilities.java:48) ~[na:na]
	at org.protege.owl.rdf.Utilities.getOwlTripleStore(Utilities.java:32) ~[na:na]
	at org.protege.editor.owl.rdf.repository.BasicSparqlReasoner.precalculate(BasicSparqlReasoner.java:54) ~[na:na]
	at org.protege.editor.owl.rdf.SparqlQueryView.initializeReasoner(SparqlQueryView.java:34) ~[na:na]
	at org.protege.editor.owl.rdf.SparqlQueryView.initialiseOWLView(SparqlQueryView.java:24) ~[na:na]
	at org.protege.editor.owl.ui.view.AbstractOWLViewComponent.initialise(AbstractOWLViewComponent.java:43) ~[na:na]
	at org.protege.editor.core.ui.view.View.createContent(View.java:413) ~[na:na]
	at org.protege.editor.core.ui.view.View.createUI(View.java:220) ~[na:na]
	at org.protege.editor.core.ui.view.View$1.hierarchyChanged(View.java:124) ~[na:na]
	at java.desktop/java.awt.Component.processHierarchyEvent(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Component.processEvent(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Container.processEvent(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Component.createHierarchyEvents(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Container.createHierarchyEvents(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Container.createHierarchyEvents(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Container.createHierarchyEvents(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Container.createHierarchyEvents(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Container.createHierarchyEvents(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Component.show(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Component.show(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Component.setVisible(Unknown Source) ~[na:na]
	at java.desktop/javax.swing.JComponent.setVisible(Unknown Source) ~[na:na]
	at java.desktop/javax.swing.JTabbedPane.fireStateChanged(Unknown Source) ~[na:na]
	at java.desktop/javax.swing.JTabbedPane$ModelListener.stateChanged(Unknown Source) ~[na:na]
	at java.desktop/javax.swing.DefaultSingleSelectionModel.fireStateChanged(Unknown Source) ~[na:na]
	at java.desktop/javax.swing.DefaultSingleSelectionModel.setSelectedIndex(Unknown Source) ~[na:na]
	at java.desktop/javax.swing.JTabbedPane.setSelectedIndexImpl(Unknown Source) ~[na:na]
	at java.desktop/javax.swing.JTabbedPane.setSelectedIndex(Unknown Source) ~[na:na]
	at java.desktop/javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(Unknown Source) ~[na:na]
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(Unknown Source) ~[na:na]
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source) ~[na:na]
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Component.processEvent(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Container.processEvent(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source) ~[na:na]
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) ~[na:na]
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) ~[na:na]
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source) ~[na:na]
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[na:na]
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source) ~[na:na]
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source) ~[na:na]
	at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[na:na]
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[na:na]
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source) ~[na:na]
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source) ~[na:na]
	at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[na:na]
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source) ~[na:na]
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) ~[na:na]
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) ~[na:na]
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) ~[na:na]
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source) ~[na:na]
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source) ~[na:na]
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source) ~[na:na]

**Comment by gouttegd** [comment]
This is the same bug as protegeproject/protege#1110.

Closing here to try to centralise the issues on the main protege repository.
